a=float(input())
b=float(input())
c=float(input())
d=float(input())
print('|%7.2f %7.2f|'%(a,b))
print('|%7.2f %7.2f|'%(c,d))
print('|{:<7.2f} {:<7.2f}|'.format(a,b))
print('|{:<7.2f} {:<7.2f}|'.format(c,d))